openapi: 3.0.0
info:
  description: maestro Service API
  title: maestro Service API
  version: 0.0.1
servers:
- description: current domain
  url: http://localhost:8000
- description: Main (production) server
  url: https://api.openshift.com
- description: Staging server
  url: https://api.stage.openshift.com
paths:
  /api/maestro/v1/resources:
    get:
      parameters:
      - description: Page number of record list when record list exceeds specified
          page size
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          minimum: 1
          type: integer
        style: form
      - description: Maximum number of records to return
        explode: true
        in: query
        name: size
        required: false
        schema:
          default: 100
          minimum: 0
          type: integer
        style: form
      - description: "Specifies the search criteria. The syntax of this parameter\
          \ is\nsimilar to the syntax of the _where_ clause of an SQL statement,\n\
          using the names of the json attributes / column names of the account. \n\
          For example, in order to retrieve all the accounts with a username\nstarting\
          \ with `my`:\n\n```sql\nusername like 'my%'\n```\n\nThe search criteria\
          \ can also be applied on related resource.\nFor example, in order to retrieve\
          \ all the subscriptions labeled by `foo=bar`,\n\n```sql\nsubscription_labels.key\
          \ = 'foo' and subscription_labels.value = 'bar'\n```\n\nIf the parameter\
          \ isn't provided, or if the value is empty, then\nall the accounts that\
          \ the user has permission to see will be\nreturned."
        explode: true
        in: query
        name: search
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Specifies the order by criteria. The syntax of this parameter is
          similar to the syntax of the _order by_ clause of an SQL statement,
          but using the names of the json attributes / column of the account.
          For example, in order to retrieve all accounts ordered by username:

          ```sql
          username asc
          ```

          Or in order to retrieve all accounts ordered by username _and_ first name:

          ```sql
          username asc, firstName asc
          ```

          If the parameter isn't provided, or if the value is empty, then
          no explicit ordering will be applied.
        explode: true
        in: query
        name: orderBy
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Supplies a comma-separated list of fields to be returned.
          Fields of sub-structures and of arrays use <structure>.<field> notation.
          <stucture>.* means all field of a structure
          Example: For each Subscription to get id, href, plan(id and kind) and labels (all fields)

          ```
          ocm get subscriptions --parameter fields=id,href,plan.id,plan.kind,labels.* --parameter fetchLabels=true
          ```
        explode: true
        in: query
        name: fields
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceList'
          description: A JSON array of resource objects
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Returns a list of resources
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
        description: Resource data
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Resource already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: An unexpected error occurred creating the resource
      security:
      - Bearer: []
      summary: Create a new resource
  /api/maestro/v1/resources/{id}:
    delete:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Resource deleted successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No resource with specified id exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error deleting resource
      security:
      - Bearer: []
      summary: Delete a resource
    get:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
          description: Resource found by id
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No resource with specified id exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Get an resource by id
    patch:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourcePatchRequest'
        description: Updated resource data
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
          description: Resource updated successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No resource with specified id exists
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Resource already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error updating resource
      security:
      - Bearer: []
      summary: Update an resource
  /api/maestro/v1/resource-bundles:
    get:
      parameters:
      - description: Page number of record list when record list exceeds specified
          page size
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          minimum: 1
          type: integer
        style: form
      - description: Maximum number of records to return
        explode: true
        in: query
        name: size
        required: false
        schema:
          default: 100
          minimum: 0
          type: integer
        style: form
      - description: "Specifies the search criteria. The syntax of this parameter\
          \ is\nsimilar to the syntax of the _where_ clause of an SQL statement,\n\
          using the names of the json attributes / column names of the account. \n\
          For example, in order to retrieve all the accounts with a username\nstarting\
          \ with `my`:\n\n```sql\nusername like 'my%'\n```\n\nThe search criteria\
          \ can also be applied on related resource.\nFor example, in order to retrieve\
          \ all the subscriptions labeled by `foo=bar`,\n\n```sql\nsubscription_labels.key\
          \ = 'foo' and subscription_labels.value = 'bar'\n```\n\nIf the parameter\
          \ isn't provided, or if the value is empty, then\nall the accounts that\
          \ the user has permission to see will be\nreturned."
        explode: true
        in: query
        name: search
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Specifies the order by criteria. The syntax of this parameter is
          similar to the syntax of the _order by_ clause of an SQL statement,
          but using the names of the json attributes / column of the account.
          For example, in order to retrieve all accounts ordered by username:

          ```sql
          username asc
          ```

          Or in order to retrieve all accounts ordered by username _and_ first name:

          ```sql
          username asc, firstName asc
          ```

          If the parameter isn't provided, or if the value is empty, then
          no explicit ordering will be applied.
        explode: true
        in: query
        name: orderBy
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Supplies a comma-separated list of fields to be returned.
          Fields of sub-structures and of arrays use <structure>.<field> notation.
          <stucture>.* means all field of a structure
          Example: For each Subscription to get id, href, plan(id and kind) and labels (all fields)

          ```
          ocm get subscriptions --parameter fields=id,href,plan.id,plan.kind,labels.* --parameter fetchLabels=true
          ```
        explode: true
        in: query
        name: fields
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceBundleList'
          description: A JSON array of resource bundle objects
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Returns a list of resource bundles
  /api/maestro/v1/resource-bundles/{id}:
    get:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceBundle'
          description: Resource bundle found by id
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No resource bundle with specified id exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Get an resource bundle by id
  /api/maestro/v1/consumers:
    get:
      parameters:
      - description: Page number of record list when record list exceeds specified
          page size
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          minimum: 1
          type: integer
        style: form
      - description: Maximum number of records to return
        explode: true
        in: query
        name: size
        required: false
        schema:
          default: 100
          minimum: 0
          type: integer
        style: form
      - description: "Specifies the search criteria. The syntax of this parameter\
          \ is\nsimilar to the syntax of the _where_ clause of an SQL statement,\n\
          using the names of the json attributes / column names of the account. \n\
          For example, in order to retrieve all the accounts with a username\nstarting\
          \ with `my`:\n\n```sql\nusername like 'my%'\n```\n\nThe search criteria\
          \ can also be applied on related resource.\nFor example, in order to retrieve\
          \ all the subscriptions labeled by `foo=bar`,\n\n```sql\nsubscription_labels.key\
          \ = 'foo' and subscription_labels.value = 'bar'\n```\n\nIf the parameter\
          \ isn't provided, or if the value is empty, then\nall the accounts that\
          \ the user has permission to see will be\nreturned."
        explode: true
        in: query
        name: search
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Specifies the order by criteria. The syntax of this parameter is
          similar to the syntax of the _order by_ clause of an SQL statement,
          but using the names of the json attributes / column of the account.
          For example, in order to retrieve all accounts ordered by username:

          ```sql
          username asc
          ```

          Or in order to retrieve all accounts ordered by username _and_ first name:

          ```sql
          username asc, firstName asc
          ```

          If the parameter isn't provided, or if the value is empty, then
          no explicit ordering will be applied.
        explode: true
        in: query
        name: orderBy
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Supplies a comma-separated list of fields to be returned.
          Fields of sub-structures and of arrays use <structure>.<field> notation.
          <stucture>.* means all field of a structure
          Example: For each Subscription to get id, href, plan(id and kind) and labels (all fields)

          ```
          ocm get subscriptions --parameter fields=id,href,plan.id,plan.kind,labels.* --parameter fetchLabels=true
          ```
        explode: true
        in: query
        name: fields
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsumerList'
          description: A JSON array of consumer objects
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Returns a list of consumers
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Consumer'
        description: Consumer data
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumer'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Consumer already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: An unexpected error occurred creating the consumer
      security:
      - Bearer: []
      summary: Create a new consumer
  /api/maestro/v1/consumers/{id}:
    delete:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Consumer deleted successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No consumer with specified id exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error deleting consumer
      security:
      - Bearer: []
      summary: Delete a consumer
    get:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumer'
          description: Consumer found by id
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No consumer with specified id exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Get an consumer by id
    patch:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsumerPatchRequest'
        description: Updated consumer data
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumer'
          description: Consumer updated successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No consumer with specified id exists
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Consumer already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error updating consumer
      security:
      - Bearer: []
      summary: Update an consumer
  /api/maestro/v1/filesyncers:
    get:
      parameters:
      - description: Page number of record list when record list exceeds specified
          page size
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          minimum: 1
          type: integer
        style: form
      - description: Maximum number of records to return
        explode: true
        in: query
        name: size
        required: false
        schema:
          default: 100
          minimum: 0
          type: integer
        style: form
      - description: "Specifies the search criteria. The syntax of this parameter\
          \ is\nsimilar to the syntax of the _where_ clause of an SQL statement,\n\
          using the names of the json attributes / column names of the account. \n\
          For example, in order to retrieve all the accounts with a username\nstarting\
          \ with `my`:\n\n```sql\nusername like 'my%'\n```\n\nThe search criteria\
          \ can also be applied on related resource.\nFor example, in order to retrieve\
          \ all the subscriptions labeled by `foo=bar`,\n\n```sql\nsubscription_labels.key\
          \ = 'foo' and subscription_labels.value = 'bar'\n```\n\nIf the parameter\
          \ isn't provided, or if the value is empty, then\nall the accounts that\
          \ the user has permission to see will be\nreturned."
        explode: true
        in: query
        name: search
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Specifies the order by criteria. The syntax of this parameter is
          similar to the syntax of the _order by_ clause of an SQL statement,
          but using the names of the json attributes / column of the account.
          For example, in order to retrieve all accounts ordered by username:

          ```sql
          username asc
          ```

          Or in order to retrieve all accounts ordered by username _and_ first name:

          ```sql
          username asc, firstName asc
          ```

          If the parameter isn't provided, or if the value is empty, then
          no explicit ordering will be applied.
        explode: true
        in: query
        name: orderBy
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Supplies a comma-separated list of fields to be returned.
          Fields of sub-structures and of arrays use <structure>.<field> notation.
          <stucture>.* means all field of a structure
          Example: For each Subscription to get id, href, plan(id and kind) and labels (all fields)

          ```
          ocm get subscriptions --parameter fields=id,href,plan.id,plan.kind,labels.* --parameter fetchLabels=true
          ```
        explode: true
        in: query
        name: fields
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileSyncerList'
          description: A JSON array of filesyncer objects
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Returns a list of filesyncers
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileSyncer'
        description: File syncer data
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileSyncer'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: File syncer already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: An unexpected error occurred creating the file syncer
      security:
      - Bearer: []
      summary: Create a new filesyncer
  /api/maestro/v1/filesyncers/{id}:
    delete:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: File syncer deleted successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No file syncer with specified id exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error deleting file syncer
      security:
      - Bearer: []
      summary: Delete a file syncer
    get:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileSyncer'
          description: File syncer found by id
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No file syncer with specified id exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Get a file syncer by id
    patch:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileSyncerPatchRequest'
        description: Updated file syncer data
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileSyncer'
          description: File syncer updated successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No file syncer with specified id exists
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: File syncer already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error updating file syncer
      security:
      - Bearer: []
      summary: Update a file syncer
components:
  parameters:
    id:
      description: The id of record
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: string
      style: simple
    page:
      description: Page number of record list when record list exceeds specified page
        size
      explode: true
      in: query
      name: page
      required: false
      schema:
        default: 1
        minimum: 1
        type: integer
      style: form
    size:
      description: Maximum number of records to return
      explode: true
      in: query
      name: size
      required: false
      schema:
        default: 100
        minimum: 0
        type: integer
      style: form
    search:
      description: "Specifies the search criteria. The syntax of this parameter is\n\
        similar to the syntax of the _where_ clause of an SQL statement,\nusing the\
        \ names of the json attributes / column names of the account. \nFor example,\
        \ in order to retrieve all the accounts with a username\nstarting with `my`:\n\
        \n```sql\nusername like 'my%'\n```\n\nThe search criteria can also be applied\
        \ on related resource.\nFor example, in order to retrieve all the subscriptions\
        \ labeled by `foo=bar`,\n\n```sql\nsubscription_labels.key = 'foo' and subscription_labels.value\
        \ = 'bar'\n```\n\nIf the parameter isn't provided, or if the value is empty,\
        \ then\nall the accounts that the user has permission to see will be\nreturned."
      explode: true
      in: query
      name: search
      required: false
      schema:
        type: string
      style: form
    orderBy:
      description: |-
        Specifies the order by criteria. The syntax of this parameter is
        similar to the syntax of the _order by_ clause of an SQL statement,
        but using the names of the json attributes / column of the account.
        For example, in order to retrieve all accounts ordered by username:

        ```sql
        username asc
        ```

        Or in order to retrieve all accounts ordered by username _and_ first name:

        ```sql
        username asc, firstName asc
        ```

        If the parameter isn't provided, or if the value is empty, then
        no explicit ordering will be applied.
      explode: true
      in: query
      name: orderBy
      required: false
      schema:
        type: string
      style: form
    fields:
      description: |-
        Supplies a comma-separated list of fields to be returned.
        Fields of sub-structures and of arrays use <structure>.<field> notation.
        <stucture>.* means all field of a structure
        Example: For each Subscription to get id, href, plan(id and kind) and labels (all fields)

        ```
        ocm get subscriptions --parameter fields=id,href,plan.id,plan.kind,labels.* --parameter fetchLabels=true
        ```
      explode: true
      in: query
      name: fields
      required: false
      schema:
        type: string
      style: form
  schemas:
    ObjectReference:
      properties:
        id:
          type: string
        kind:
          type: string
        href:
          type: string
      type: object
    List:
      properties:
        kind:
          type: string
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
      required:
      - items
      - kind
      - page
      - size
      - total
      type: object
    Error:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - properties:
          code:
            type: string
          reason:
            type: string
          operation_id:
            type: string
        type: object
      example:
        reason: reason
        code: code
        kind: kind
        operation_id: operation_id
        id: id
        href: href
    ErrorList:
      allOf:
      - $ref: '#/components/schemas/List'
      - properties:
          items:
            items:
              $ref: '#/components/schemas/Error'
            type: array
        type: object
    Resource:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - properties:
          name:
            type: string
          consumer_name:
            type: string
          version:
            type: integer
          created_at:
            format: date-time
            type: string
          updated_at:
            format: date-time
            type: string
          deleted_at:
            format: date-time
            type: string
          manifest:
            $ref: '#/components/schemas/Resource_allOf_manifest'
          delete_option:
            $ref: '#/components/schemas/Resource_allOf_manifest'
          update_strategy:
            $ref: '#/components/schemas/Resource_allOf_manifest'
          status:
            $ref: '#/components/schemas/Resource_allOf_manifest'
        type: object
      example:
        delete_option: null
        kind: kind
        manifest: null
        created_at: 2000-01-23T04:56:07.000+00:00
        version: 5
        deleted_at: 2000-01-23T04:56:07.000+00:00
        consumer_name: consumer_name
        updated_at: 2000-01-23T04:56:07.000+00:00
        update_strategy: null
        name: name
        id: id
        href: href
        status: null
    ResourceList:
      allOf:
      - $ref: '#/components/schemas/List'
      - properties:
          items:
            items:
              $ref: '#/components/schemas/Resource'
            type: array
        type: object
      example:
        total: 1
        size: 6
        kind: kind
        page: 0
        items:
        - delete_option: null
          kind: kind
          manifest: null
          created_at: 2000-01-23T04:56:07.000+00:00
          version: 5
          deleted_at: 2000-01-23T04:56:07.000+00:00
          consumer_name: consumer_name
          updated_at: 2000-01-23T04:56:07.000+00:00
          update_strategy: null
          name: name
          id: id
          href: href
          status: null
        - delete_option: null
          kind: kind
          manifest: null
          created_at: 2000-01-23T04:56:07.000+00:00
          version: 5
          deleted_at: 2000-01-23T04:56:07.000+00:00
          consumer_name: consumer_name
          updated_at: 2000-01-23T04:56:07.000+00:00
          update_strategy: null
          name: name
          id: id
          href: href
          status: null
    ResourcePatchRequest:
      example:
        delete_option: "{}"
        update_strategy: "{}"
        manifest: "{}"
        version: 0
      properties:
        version:
          type: integer
        manifest:
          type: object
        delete_option:
          type: object
        update_strategy:
          type: object
      type: object
    ResourceBundleList:
      allOf:
      - $ref: '#/components/schemas/List'
      - properties:
          items:
            items:
              $ref: '#/components/schemas/ResourceBundle'
            type: array
        type: object
      example:
        total: 1
        size: 6
        kind: kind
        page: 0
        items:
        - metadata: null
          delete_option: null
          kind: kind
          created_at: 2000-01-23T04:56:07.000+00:00
          version: 5
          deleted_at: 2000-01-23T04:56:07.000+00:00
          manifest_configs:
          - "{}"
          - "{}"
          consumer_name: consumer_name
          updated_at: 2000-01-23T04:56:07.000+00:00
          name: name
          manifests:
          - "{}"
          - "{}"
          id: id
          href: href
          status: null
        - metadata: null
          delete_option: null
          kind: kind
          created_at: 2000-01-23T04:56:07.000+00:00
          version: 5
          deleted_at: 2000-01-23T04:56:07.000+00:00
          manifest_configs:
          - "{}"
          - "{}"
          consumer_name: consumer_name
          updated_at: 2000-01-23T04:56:07.000+00:00
          name: name
          manifests:
          - "{}"
          - "{}"
          id: id
          href: href
          status: null
    ResourceBundle:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - properties:
          name:
            type: string
          consumer_name:
            type: string
          version:
            type: integer
          created_at:
            format: date-time
            type: string
          updated_at:
            format: date-time
            type: string
          deleted_at:
            format: date-time
            type: string
          metadata:
            $ref: '#/components/schemas/Resource_allOf_manifest'
          manifests:
            items:
              type: object
            type: array
          delete_option:
            $ref: '#/components/schemas/Resource_allOf_manifest'
          manifest_configs:
            items:
              type: object
            type: array
          status:
            $ref: '#/components/schemas/Resource_allOf_manifest'
        type: object
      example:
        metadata: null
        delete_option: null
        kind: kind
        created_at: 2000-01-23T04:56:07.000+00:00
        version: 5
        deleted_at: 2000-01-23T04:56:07.000+00:00
        manifest_configs:
        - "{}"
        - "{}"
        consumer_name: consumer_name
        updated_at: 2000-01-23T04:56:07.000+00:00
        name: name
        manifests:
        - "{}"
        - "{}"
        id: id
        href: href
        status: null
    Consumer:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - properties:
          name:
            type: string
          labels:
            additionalProperties:
              type: string
            type: object
          created_at:
            format: date-time
            type: string
          updated_at:
            format: date-time
            type: string
        type: object
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        kind: kind
        name: name
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        href: href
        labels:
          key: labels
    ConsumerList:
      allOf:
      - $ref: '#/components/schemas/List'
      - properties:
          items:
            items:
              $ref: '#/components/schemas/Consumer'
            type: array
        type: object
      example:
        total: 1
        size: 6
        kind: kind
        page: 0
        items:
        - updated_at: 2000-01-23T04:56:07.000+00:00
          kind: kind
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          href: href
          labels:
            key: labels
        - updated_at: 2000-01-23T04:56:07.000+00:00
          kind: kind
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          href: href
          labels:
            key: labels
    ConsumerPatchRequest:
      example:
        labels:
          key: labels
      properties:
        labels:
          additionalProperties:
            type: string
          type: object
      type: object
    FileSyncer:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - properties:
          consumer_name:
            type: string
          version:
            type: integer
          created_at:
            format: date-time
            type: string
          updated_at:
            format: date-time
            type: string
          deleted_at:
            format: date-time
            type: string
          spec:
            $ref: '#/components/schemas/Resource_allOf_manifest'
          status:
            $ref: '#/components/schemas/Resource_allOf_manifest'
        type: object
      example:
        consumer_name: consumer_name
        updated_at: 2000-01-23T04:56:07.000+00:00
        kind: kind
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        href: href
        version: 5
        deleted_at: 2000-01-23T04:56:07.000+00:00
        spec: null
        status: null
    FileSyncerSpec:
      properties:
        files:
          items:
            $ref: '#/components/schemas/FileObject'
          type: array
      type: object
    FileObject:
      properties:
        name:
          type: string
        content:
          type: string
        verfication:
          type: string
        path:
          type: string
        mode:
          type: integer
        overwrite:
          type: boolean
        user:
          type: string
        group:
          type: string
      type: object
    FileSyncerPatchRequest:
      example:
        spec: "{}"
      properties:
        spec:
          type: object
      type: object
    FileSyncerList:
      allOf:
      - $ref: '#/components/schemas/List'
      - properties:
          items:
            items:
              $ref: '#/components/schemas/FileSyncer'
            type: array
        type: object
      example:
        total: 1
        size: 6
        kind: kind
        page: 0
        items:
        - consumer_name: consumer_name
          updated_at: 2000-01-23T04:56:07.000+00:00
          kind: kind
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          href: href
          version: 5
          deleted_at: 2000-01-23T04:56:07.000+00:00
          spec: null
          status: null
        - consumer_name: consumer_name
          updated_at: 2000-01-23T04:56:07.000+00:00
          kind: kind
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          href: href
          version: 5
          deleted_at: 2000-01-23T04:56:07.000+00:00
          spec: null
          status: null
    Resource_allOf_manifest:
      type: object
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      scheme: bearer
      type: http
